# -*- coding: utf-8 -*-
"""colortexto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dawo022BxbfzmoGXFrsh0VqzPq4HzYCi
"""

def tablaformatos():
    for estilo in range(8):
        for colortexto in range(30,38):
            cad_cod = ''
            for colorfondo in range(40,48):
                fmto =';'.join([str(estilo),
                str(colortexto),
                str(colorfondo)])
                cad_cod+="\033["+fmto+"m "+fmto+" \033[0m"
            print(cad_cod)
        print('\n')

tablaformatos()