# -*- coding: utf-8 -*-
"""config1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5tzoizUvYACNhxyFFTmj-uB8ICS3YsN
"""

TITULO="Python GUI"
COLOR_BARRA_SUPERIOR="#333333"
COLOR_MENU_LATERAL="#555555"
COLOR_PANEL_PRINCIPAL= "#CCCCCC"