# -*- coding: utf-8 -*-
"""EXE1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5tzoizUvYACNhxyFFTmj-uB8ICS3YsN
"""

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('imagenes', 'imagenes'), ('fuentes', 'fuentes')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Mi Punto de Venta',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['imagenes\\sales.ico'],
)