# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CP0HowyGSOA6twSs_21gUazFgIMoAtQf
"""



import random

respuestas = [
    "Es posible.",
    "SI.",
    "Sin dudaS.",
    "Definitivamente.",
    "Cuidao.",
    "Según mi punto de vista no",
    "Es muy probable.",
    "tenlo en cuenta.",
    "Sí.",
    "no te bases en señales.",
    "Respuesta confusa, intenta de nuevo.",
    "piensalo",
    "Mejor que no lo sepas",
    "No se puede predecir aun.",
    "pregunta de nuevo.",
    "No te bases en una corazonada.",
    "Mi respuesta es no.",
    "Mis fuentes dicen que no.",
    "Analizalo de otro modo.",
    "lo dudo."
]
while True:
    pregunta = input("Pregunta: ")
    if pregunta.lower() == "salir":
        break
    respuesta = random.choice(respuestas)
    print(respuesta)
def bola8():
    """Simula una Bola 8 mágica y devuelve un mensaje aleatorio."""
    return random.choice(messages)

# Ejemplo de uso:
print("Agita la bola 8 y descubre tu suerte:")
print(bola8())