# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szH1W64vqgxKQTZAiGriZBcrfOyAPg0_
"""

info_tienda = ("Game On!", 2010)

inventario = {
"Zelda: Breath of the Wild": {"precio": 1200, "stock": 5},
"Halo: Combat Evolved": {"precio": 800, "stock": 3},
"Dishonored": {"precio": 600, "stock": 4}
}

segundo_juego = list(inventario.keys())[1]
print(f"El precio de '{segundo_juego}' es: ${inventario[segundo_juego]['precio']}")

primer_juego = list(inventario.keys())[0]
inventario[primer_juego]["stock"] -= 1

print(f"\nVendiste una copia de '{primer_juego}'.")
print(f"Stock actual: {inventario[primer_juego]['stock']} unidades")

print("\nInventario actualizado:")
for juego, datos in inventario.items():
    print(f"{juego}: ${datos['precio']} | Stock: {datos['stock']}")

