# -*- coding: utf-8 -*-
"""videojuegos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUZEpMt0HG6jcnNXyk6kwJj5faBCZdBq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

sales_data = {
    "GameID": ["G1","G2","G3","G4","G5","G6"],
    "Title": ["ZeldaBOTW","ZeldaOOT"
              ,"Dishonored","HaloCE"
              ,"Zelda Majoras Mask","PvZ"],
    "Genre": ["Aventura","Aventura","Aventura","Aventura","Aventura","Aventura"],
    "Publisher":["Nintendo","Nintendo","Nintendo"
                 ,"Nintendo","Nintendo","Nintendo"],
    "Units_Sold_Millions":[10.0,20.0,1.0,7.1,11.7,11.7]
}

sales_df = pd.DataFrame(sales_data)

reviews_data= {
    "GameID": ["G1","G2","G3","G4","G5","G7"],
    "Critic_Score":[10.0,10.0,10.0,9.0,9.9,9.9],
    "User_Score": [5.1,9.1,8.5,9.2,np.nan,7.5]
}

reviews_df = pd.DataFrame(reviews_data)

print("--- Datos de Ventas (crudos) ---")
print(sales_df)
print("--- Datos de Reseñas (crudos) ---")
print(reviews_df)

mean_user_score = reviews_df["User_Score"].mean()
reviews_df["User_Score"] = reviews_df["User_Score"].fillna(mean_user_score)

print(f"\n--- Reseñas (Limpias,NaN rellenado con {mean_user_score})---")
print(reviews_df)

df = pd.merge(sales_df,reviews_df, on="GameID", how="inner")

print("\n--- Tabla fusionada de ventas+reseñas ---")
print(df)

df["Revenue_Estimate_Billions"] = (df["Units_Sold_Millions"]*50)/1000

df["Score_Gap"] = df["Critic_Score"]-df["User_Score"]

df["Critic_Score_100"] = df["Critic_Score"] * 10

print("\n--- Tabla transformada (Con nuevas Columnas)")
print(df)

genre_sales = df.groupby("Genre")["Units_Sold_Millions"]
sum().sort_values(ascending=False)