# -*- coding: utf-8 -*-
"""WORDLE12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDvL18oPCh8Ef6ewhLZrxsPEMkjHmEpR
"""

import random
palabras = ("abrir", "actor", "reloj", "acaso", "jugod", "brawl")
while True:
    palabra = palabras[random.randint(0, len(palabras)-1)] #abajo
    wordle = list(palabra)
    print("""\033(1;37:44m)
====================[wordle]====================
Tienes5intentospara adivinarla
================================================
\033[0;30;47m""")
    correct_guess = False
    for i in range(5):
        intento = input("ingrese una palabra: ").lower()[:5]
        indice = 0
        resultado = ""
        correct_letters = 0
        for letra in intento:
            if letra == wordle[indice]:
                resultado += "\033[1;32m" + letra + "\033[0;37;40m"
                correct_letters += 1
            elif letra in wordle:
                resultado += "\033[1;33m" + letra + "\033[0;37;40m"
            else:
                resultado += "\033[1;31m" + letra + "\033[0;37;40m"
            indice += 1
        print(resultado)
        if correct_letters == 5:
            print(f"felicidades,la palabra era \033(1;32m{palabra})\033[0;37;40m")
            correct_guess = True
            break

    if not correct_guess:
        print(f"Lo siento, no adivinaste la palabra. Era \033(1;32m{palabra})\033[0;37;40m")

    while True:
        jugar_de_nuevo = input("¿Quieres jugar de nuevo? (si/no): ").lower()
        if jugar_de_nuevo in ["si", "no"]:
            break
        else:
            print("Por favor, responde 'si' o 'no'.")

    if jugar_de_nuevo == "no":
        break